module.exports = {
  AntDesign: require('./AntDesign.ttf'),
  Entypo: require('./Entypo.ttf'),
  EvilIcons: require('./EvilIcons.ttf'),
  Feather: require('./Feather.ttf'),
  FontAwesome: require('./FontAwesome.ttf'),
  FontAwesome5_Solid: require('./FontAwesome5_Solid.ttf'),
  FontAwesome5_Regular: require('./FontAwesome5_Regular.ttf'),
  FontAwesome5_Brands: require('./FontAwesome5_Brands.ttf'),
  Foundation: require('./Foundation.ttf'),
  Ionicons: require('./Ionicons.ttf'),
  MaterialCommunityIcons: require('./MaterialCommunityIcons.ttf'),
  MaterialIcons: require('./MaterialIcons.ttf'),
  SimpleLineIcons: require('./SimpleLineIcons.ttf'),
  Octicons: require('./Octicons.ttf'),
  Zocial: require('./Zocial.ttf'),
};
